### ISSUE TITLE
 no wasmedge-tensorflow binary in WasmEdge-tensorflow-tools for Android 

### ISSUE THREAD

**Issue by chairwa** [second-state/WasmEdge-tensorflow-tools#2]
Only wasmedge-tensorflow-lite & show-tflite-tensor are included in WasmEdge-tensorflow-tools release for Android,  no wasmedge-tensorflow binary there. I wonder why, Android only support tflite ?

**Comment by hydai** [comment]
Hi @chairwa 
Because the upstream doesn't officially provide the support for the android platform. For android, the only option is using tensorflow-lite: https://www.tensorflow.org/lite/android.
